[package]
name = "web3_credit_card"
version = "0.1.0"
edition = "2023_10"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.16.0" }
starknet = "2.6.3"

[[target.starknet-contract]]
casm = true
