import React from 'react'
import { Contract, Account, Provider } from 'starknet'
// Create a file called abi.json in  your assets folder under src and paste the sierra.json file generated by scarb build that you declared earlier.
import { abi } from './assets/abi.json'

const PRIVATE_KEY = process.env.PRIVATE_KEY // Pick an account and pass its private key here
const ACCOUNT_ADDRESS = "0x29724d03151eff483f60b7f556593beb1f600bac9b5372240f924bc5b07fe18" // Account address of the selected account from starknet-devnet

/* The contract address below is modified, also modify yours and remove any zeros after x ie
if your contract address is 0x004236... or 0x04236... - remove the two/one zero(s) after x to be
0x4236...
*/
const CONTRACT_ADDRESS = import.meta.env.CONTRACT_ADDRESS // Contract address

const provider = new Provider({ rpc: { nodeUrl: 'https://free-rpc.nethermind.io/sepolia-juno/v0_7' } })
const account = new Account(provider, ACCOUNT_ADDRESS, PRIVATE_KEY)
const contract = new Contract(abi, CONTRACT_ADDRESS, account)

const App = () => {
console.log(PRIVATE_KEY)
async function callContract(){
    const res = await contract.get_balance()
    console.log(res.toString())
}

async function writeToContract(){
    contract.connect(account)
    const myCall = contract.populate('increase_balance', [35])
    const res = await contract.increase_balance(myCall.calldata)
    console.log(res)
}

return (
    <div>
    <button onClick={callContract}>Call Contract</button>
    <button onClick={writeToContract}>Write to Contract</button>
    </div>
)
}

export default App
